server:
  port: 8080
spring:
  application:
    name: gateway
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8846/oauth/key
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/oauth/**
        - id: announcement-service
          uri: lb://announcement-service
          predicates:
            - Path=/api/announcements/**
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/attendances/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**,/api/profile-pictures/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/depts/**,/api/roles/**,/api/permissions
        - id: message-service
          uri: lb://chat-service
          predicates:
            - Path=/api/messages/**
        - id: chat-service
          uri: lb:ws://chat-service
          predicates:
            - Path=/api/chat/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/searches/**